rtl/pkg/axi_pkg.sv
rtl/pkg/prolepsis_pkg.sv
rtl/interfaces/axi4_lite_if.sv
rtl/interfaces/telemetry_if.sv

rtl/Orionrv.sv
rtl/accelerator/MAC_Unit.sv
rtl/bus/Address_Decoder.sv
rtl/bus/AXI_Interconnect.sv
rtl/bus/AXI_Master_Wrapper.sv
rtl/bus/AXI_Slave_Wrapper.sv
rtl/bus/QoS_Arbiter.sv
rtl/cache/Instruction_Cache.sv
rtl/cache/Data_Cache.sv
rtl/cache/Victim_Buffer.sv
rtl/cache/Stride_Prefetcher.sv
rtl/core/Branch_Predictor.sv
rtl/core/Branch_Unit.sv
rtl/core/Loop_Buffer.sv
rtl/core/RVC_Decompressor.sv
rtl/core/CSR_Unit.sv
rtl/core/Decoder.sv
rtl/core/Hazard_Unit.sv
rtl/core/Imm_Gen.sv
rtl/core/Pipelined_ALU.sv
rtl/core/Register_File.sv
rtl/core/RV32_Core.sv
rtl/peripherals/Boot_ROM.sv
rtl/peripherals/Seven_Seg_Driver.sv
rtl/peripherals/Timer.sv
rtl/peripherals/UART.sv
rtl/thermal/Kalman_Predictor.sv
rtl/thermal/Migration_Policy.sv
rtl/thermal/Migration_Controller.sv
rtl/thermal/Cache_Warmer.sv
rtl/thermal/Power_Gate_Controller.sv
rtl/thermal/Eval_Framework.sv
rtl/thermal/Phase_Detector.sv
rtl/thermal/QoS_Adjuster.sv
rtl/thermal/Thermal_Controller.sv
rtl/thermal/Thermal_Sensor.sv
